name: Deploy Frontend to Vercel

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: team_gQDvKxvTMjDU1hFGMXnlYjD5
          vercel-project-id: prj_gvA59wyrUJUoJY4qs1jofVOudOGx
          working-directory: ./frontend
          vercel-args: '--prod'
